add juju 3.4 support
canonical/charm-juju-local pull request #12
Opened 2024-04-22 20:59 UTC by zxhdaze

Add juju 3.4 support, add concurrency

2024-04-23 20:24 UTC, rgildein requested changes
I really think that for this one we should use official GitHub runner and nested containers or use constraints to define vm for juju-local. Using self-hosted runner and external OpenStack is huge waste of resources.

Also we need to use juju-channel in the bundle and drop any `juju3` bundle, e.g. [focal-juju3.yaml](https://github.com/canonical/charm-juju-local/blob/master/tests/functional/tests/bundles/overlays/focal-juju3.yaml.j2).

2024-04-24 11:35 UTC, rgildein requested changes

2024-04-24 11:35 UTC, rgildein commented on tests/functional/tests/bundles/base.yaml
> +    constraints: virt-type=virtual-machine
I was testing this manually why it's not working, and after while I realized that you are defining `constraints` in two places, in machines and here. Please move this configuration to line 4.

2024-04-25 10:29 UTC, rgildein approved these changes
LGTM, thanks for effort.

2024-04-26 05:59 UTC, Pjack approved these changes

2024-04-26 13:01 UTC, merged