ci: enable github workflow
canonical/charm-juju-local pull request #9
Opened 2023-12-21 06:04 UTC by jneo8

2023-12-27 06:13 UTC, jneo8 commented
pause because this charm will try to setup an ubuntu unit and bootstrap juju controller inside. It's not possible for lxd container cloud.

2023-12-28 08:49 UTC, jneo8 commented
Fail because this charm will bootstrap new controller in the unit, so it required vm machine to used.

2024-01-23 08:12 UTC, sudeephb approved these changes

2024-01-23 08:48 UTC, dashmage requested changes
I've left a few comments which might need some input from you.

2024-01-23 08:48 UTC, dashmage commented on tests/functional/requirements.txt
> +git+https://github.com/jneo8/zaza.git@libjuju-3.1-config-cred#egg=zaza
We can directly use the `libjuju-3.1` branch from upstream since the changes for configuring credentials has been merged.

2024-01-23 08:48 UTC, dashmage commented on tox.ini
> +changedir = {toxinidir}/tests/functional
Do we need the `changedir` key if all we're doing is just printing that the unit tests aren't available?

2024-01-23 08:50 UTC, dashmage commented
One additional request would be to explicitly mention somewhere (separate commit for example) that we're deprecating bionic support with this PR. It would be easier to grep for later on if we want to find the exact commit.

2024-01-24 14:42 UTC, Pjack approved these changes

2024-01-24 15:11 UTC, dashmage approved these changes
LGTM now, thanks for addressing my comments!

2024-01-25 07:11 UTC, merged